# Generated by Django 2.2.6 on 2020-03-27 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 27, 7, 41, 26, 190322, tzinfo=utc))),
            ],
        ),
    ]
